name: applied_nurses
description: A new Flutter project.
version: 1.0.5+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.1.0+1
  animations: ^2.0.8
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  change_app_package_name: ^1.1.0
  connectivity_plus: null
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.0
  easy_localization: ^3.0.3
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0+1
  flutter_dotenv: ^5.0.2
  flutter_image_stack: ^0.0.6
  flutter_riverpod: ^2.3.6
  flutter_screenutil: ^5.5.4
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  iconly: ^1.0.1
  image_picker: ^1.0.1
  injectable: null
  intl: ^0.18.0
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  pin_code_fields: ^8.0.1
  pinput: ^3.0.1
  pretty_dio_logger: ^1.2.0-beta-1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.9
  webview_flutter: ^4.0.2

dev_dependencies:
  build_runner: null
  flutter_test:
    sdk: flutter
  freezed: null
  json_serializable: null
  lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/languages/
    - assets/images/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
